apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: org1-peer1-peer-pvc
 labels:
   billingType: hourly
 namespace: blockchain
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 100Gi
 storageClassName: ibmc-file-bronze
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: org1-peer1-couchdb-pvc
 labels:
   billingType: hourly
 namespace: blockchain
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 100Gi
 storageClassName: ibmc-file-bronze