# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: ordererorg
    EnableNodeOUs: true

    CA:
      Hostname: ca
      CommonName: ordererorgca

    Specs:
      - Hostname: ordererorg-orderer1
        CommonName: "{{.Hostname}}"
        SANS:
          - "*.127.0.0.1.xip.io"
          - "localhost"
          - "10.9.211.106" # TOCHANGE: Add your worker node here (for free IKS cluster) or LoadBalancer IP
          - "10.9.211.107"
          - "10.9.211.193"
          - "ordererorg-orderer1.dscf.svc.cluster.local"
      - Hostname: ordererorg-orderer2
        CommonName: "{{.Hostname}}"
        SANS:
          - "*.127.0.0.1.xip.io"
          - "localhost"
          - "10.9.211.106" # TOCHANGE: Add your worker node here (for free IKS cluster) or LoadBalancer IP
          - "10.9.211.107"
          - "10.9.211.193"
          - "ordererorg-orderer2.dscf.svc.cluster.local"
      - Hostname: ordererorg-orderer3
        CommonName: "{{.Hostname}}"
        SANS:
          - "*.127.0.0.1.xip.io"
          - "localhost"
          - "10.9.211.106" # TOCHANGE: Add your worker node here (for free IKS cluster) or LoadBalancer IP
          - "10.9.211.107"
          - "10.9.211.193"
          - "ordererorg-orderer3.dscf.svc.cluster.local"
    Users:
        Count: 2

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:

  - Name: KTB
    Domain: ktborg
    EnableNodeOUs: true

    CA:
      Hostname: ca
      CommonName: ktbca

    Specs:
      - Hostname: ktborg-peer1
        CommonName: "{{.Hostname}}"
        SANS:
          - "*.127.0.0.1.xip.io"
          - "localhost"
          - "10.9.211.106" # TOCHANGE: Add your worker node here (for free IKS cluster) or LoadBalancer IP
          - "10.9.211.107"
          - "10.9.211.193"
          - "ktborg-peer1.dscf.svc.cluster.local"
      - Hostname: ktborg-peer2
        CommonName: "{{.Hostname}}"
        SANS:
          - "*.127.0.0.1.xip.io"
          - "localhost"
          - "10.9.211.106" # TOCHANGE: Add your worker node here (for free IKS cluster) or LoadBalancer IP
          - "10.9.211.107"
          - "10.9.211.193"
          - "ktborg-peer2.dscf.svc.cluster.local"