---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    run: couchdb
  namespace: dscf
spec:
  type: NodePort
  selector:
    name: couchdb
  ports:
  - protocol: TCP
    port: 5984
    targetPort: 5984
    nodePort: 31985
    name: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: dscf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: couchdb
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: db
        image: couchdb:3.1.0
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: data
        env:
         - name: COUCHDB_USER
           value: admin
         - name: COUCHDB_PASSWORD
           value: pass
        ports:
         - containerPort: 5984
           protocol: TCP