---
apiVersion: v1
kind: Pod
metadata:
  name: utility-pod
  namespace: dscf
spec:
  restartPolicy: "Never"
  volumes:
  - name: tmp
    emptyDir: {}
  - name: admin-ktborg
    secret:
      secretName: admin-ktborg-crypto
      items:
      - key: admincert.pem
        path: admincerts/admincert.pem
      - key: cacert.pem
        path: cacerts/cacert.pem
      - key: cert.pem
        path: signcerts/cert.pem
      - key: key
        path: keystore/key
      - key: tlscacert.pem
        path: tlscacerts/tlscacert.pem
  - name: admin-ordererorg
    secret:
      secretName: admin-ordererorg-crypto
      items:
      - key: admincert.pem
        path: admincerts/admincert.pem
      - key: cacert.pem
        path: cacerts/cacert.pem
      - key: cert.pem
        path: signcerts/cert.pem
      - key: key
        path: keystore/key
      - key: tlscacert.pem
        path: tlscacerts/tlscacert.pem
  # ktborg
  - name: ktborg-peer1-tls
    secret:
      secretName: ktborg-peer1-tlsca-crypto
  - name: ktborg-peer2-tls
    secret:
      secretName: ktborg-peer2-tlsca-crypto
  # ordererorg
  - name: ordererorg-orderer1-tls
    secret:
      secretName: ordererorg-orderer1-tlsca-crypto
  - name: ordererorg-orderer2-tls
    secret:
      secretName: ordererorg-orderer2-tlsca-crypto
  - name: ordererorg-orderer3-tls
    secret:
      secretName: ordererorg-orderer3-tlsca-crypto
  # channel
  - name: document-genesis-channel
    configMap:
      name: document-genesis
  - name: document-verifier-genesis-channel
    configMap:
      name: document-verifier-genesis
  - name: public-key-genesis-channel
    configMap:
      name: public-key-genesis
  # anchor
  - name: document-anchorpeer-ktborg
    configMap: 
      name: document-anchorpeer-ktborg
  - name: document-verifier-anchorpeer-ktborg
    configMap: 
      name: document-verifier-anchorpeer-ktborg
  - name: public-key-anchorpeer-ktborg
    configMap: 
      name: public-key-anchorpeer-ktborg
  containers:
  - name: util
    image: kcskbcnd93.kcs:5000/hyperledger/fabric-tools:2.2.1
    imagePullPolicy: IfNotPresent
    command: [ "sh", "-c", "--" ]
    args: [ "trap : TERM INT; sleep infinity & wait" ]
    env:
        - name: GOPATH
          value: /go
        - name: CHANNEL_NAME
          value: channel1
        - name: CHAINCODE_NAME
          value: fabcar
        - name: CHAINCODE_VERSION
          value: "1"
        - name: ORDERER_URL
          value: ordererorg-orderer1:7050
        - name: ORDERER_CA_TLS
          value: /crypto/ordererorg/orderers/ordererorg-orderer1/tls/ca.crt
        - name: CORE_PEER_ADDRESS
          value: ktborg-peer1:7051
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /crypto/ktborg/peers/ktborg-peer1/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /crypto/ktborg/peers/ktborg-peer1/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /crypto/ktborg/peers/ktborg-peer1/tls/ca.crt
        - name: CORE_PEER_LOCALMSPID
          value: KTBOrgMSP
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_PEER_MSPCONFIGPATH
          value: /crypto/ktborg/users/Admin@ktborg/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: /crypto/ktborg/users/Admin@ktborg/msp
      name: admin-ktborg
      readOnly: true
    - mountPath: /crypto/ordererorg/users/Admin@ordererorg/msp
      name: admin-ordererorg
      readOnly: true
    - mountPath: /crypto/ktborg/peers/ktborg-peer1/tls
      name: ktborg-peer1-tls
      readOnly: true
    - mountPath: /crypto/ktborg/peers/ktborg-peer2/tls
      name: ktborg-peer2-tls
      readOnly: true
    - mountPath: /crypto/ordererorg/orderers/ordererorg-orderer1/tls
      name: ordererorg-orderer1-tls
      readOnly: true
    - mountPath: /crypto/ordererorg/orderers/ordererorg-orderer2/tls
      name: ordererorg-orderer2-tls
      readOnly: true
    - mountPath: /crypto/ordererorg/orderers/ordererorg-orderer3/tls
      name: ordererorg-orderer3-tls
      readOnly: true
    - mountPath: /data-document-genesis-channel
      name: document-genesis-channel
    - mountPath: /data-document-verifier-genesis-channel
      name: document-verifier-genesis-channel
    - mountPath: /data-public-key-genesis-channel
      name: public-key-genesis-channel
    - mountPath: /anchorpeers/ktborg-document
      name: document-anchorpeer-ktborg
    - mountPath: /anchorpeers/ktborg-document-verifier
      name: document-verifier-anchorpeer-ktborg
    - mountPath: /anchorpeers/ktborg-public-key
      name: public-key-anchorpeer-ktborg
    - mountPath: /tmp
      name: tmp