---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: blockchain-api
  name: blockchain-api
  namespace: dscf # guarantor-api, blockchain, default
spec:
  selector:
    matchLabels:
      name: blockchain-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: blockchain-api
    spec:
      containers:
      - name: blockchain-api
        image: kcskbcnd93.kcs:5000/hyperledger/api-test:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
