---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-api
  namespace: dscf # guarantor-api, blockchain, default
  labels:
    run: blockchain-api
spec:
  type: NodePort
  selector:
    name: blockchain-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30360
