apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer1-dscf-pvc
  namespace: dscf
  labels:
    billingType: hourly
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi