apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: orderer3-pvc
 labels:
   billingType: hourly
 namespace: blockchain
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 100Gi
 storageClassName: ibmc-file-bronze