---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1-ca
  labels:
    app: blockchain
  namespace: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      name: org1-ca
      app: blockchain
  template:
    metadata:
      labels:
        name: org1-ca
        app: blockchain
    spec:
      volumes:
      - name: data
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: org1-ca-pvc
      - name: crypto
        secret:
          secretName: org1-ca-crypto
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ibm-cloud.kubernetes.io/worker-id
                operator: In
                values:
                - kube-boe4bt5t09sb8c63dq40-sitktbscfcl-default-0000015a
      containers:
      - name: ca
        image: hyperledger/fabric-ca:1.4.9
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
        env:
        - name: FABRIC_CA_HOME
          value: /data
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: /crypto/cert.pem
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: /crypto/key
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        ports:
         - containerPort: 7054
           protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /crypto
          name: crypto
---
apiVersion: v1
kind: Service
metadata:
  name: org1-ca
  labels:
    app: blockchain
    run: org1-ca
  namespace: blockchain
spec:
  type: NodePort
  selector:
    name: org1-ca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 7054